export const intervals = [
    // true = the person responding right now has selected they want to attend this time block
    // first array is who can attend, second is who cannot
    // first integer is how many people available at that time, second integer is how many people total - for example 0/5
    [
      "09:00",
      0,
      5,
      false,
      [],
      [
        "James Junaidi",
        "Omid Mogasemi",
        "Essam Sleiman",
        "John Doe",
        "Sally Brown",
      ],
    ],
    [
      "09:30",
      2,
      5,
      false,
      ["James Junaidi", "Omid Mogasemi"],
      ["Essam Sleiman", "John Doe", "Sally Brown"],
    ],
    [
      "10:00",
      3,
      5,
      false,
      ["James Junaidi", "Omid Mogasemi", "Essam Sleiman"],
      ["John Doe", "Sally Brown"],
    ],
    [
      "10:30",
      5,
      5,
      false,
      [
        "James Junaidi",
        "Omid Mogasemi",
        "Essam Sleiman",
        "John Doe",
        "Sally Brown",
      ],
      [],
    ],
    [
      "11:00",
      3,
      5,
      false,
      ["James Junaidi", "Omid Mogasemi", "Essam Sleiman"],
      ["John Doe", "Sally Brown"],
    ],
    [
      "11:30",
      1,
      5,
      false,
      ["James Junaidi"],
      ["Omid Mogasemi", "Essam Sleiman", "John Doe", "Sally Brown"],
    ],
    [
      "12:00",
      4,
      5,
      false,
      ["James Junaidi", "Omid Mogasemi", "Essam Sleiman", "John Doe"],
      ["Sally Brown"],
    ],
    [
      "12:30",
      1,
      5,
      false,
      ["James Junaidi"],
      ["Omid Mogasemi", "Essam Sleiman", "John Doe", "Sally Brown"],
    ],
  ],
  calendar1_intervals = [
    // NOTE: The 3 different calendar's intervals are identical right now. Haven't had time to randomize them yet
    // true = something is going on in the half hour block that starts at that corresponding time
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", false],
      ["11am", false],
      ["1130m", false],
      ["12pm", false],
      ["1230pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", false],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", true],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", true],
      ["12pm", false],
      ["1230pm", false],
    ],
  ],
  calendar2_intervals = [
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", false],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", true],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", true],
      ["12pm", false],
      ["1230pm", false],
    ],
  ],
  calendar3_intervals = [
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", false],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", true],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", true],
      ["12pm", false],
      ["1230pm", false],
    ],
  ];

export default {
  calendar1_intervals,
  calendar2_intervals,
  calendar3_intervals,
};
