export const intervals = [
    [
      "9am",
      "0/5",
      false,
      [],
      [
        "James Junaidi",
        "Omid Mogasemi",
        "Essam Sleiman",
        "John Doe",
        "Sally Brown",
      ],
    ],
    [
      "930am",
      "2/5",
      false,
      ["James Junaidi", "Omid Mogasemi"],
      ["Essam Sleiman", "John Doe", "Sally Brown"],
    ],
    [
      "10am",
      "3/5",
      false,
      ["James Junaidi", "Omid Mogasemi", "Essam Sleiman"],
      ["John Doe", "Sally Brown"],
    ],
    [
      "1030am",
      "5/5",
      false,
      [
        "James Junaidi",
        "Omid Mogasemi",
        "Essam Sleiman",
        "John Doe",
        "Sally Brown",
      ],
      [],
    ],
    [
      "11am",
      "3/5",
      false,
      ["James Junaidi", "Omid Mogasemi", "Essam Sleiman"],
      ["John Doe", "Sally Brown"],
    ],
    [
      "1130am",
      "1/5",
      false,
      ["James Junaidi"],
      ["Omid Mogasemi", "Essam Sleiman", "John Doe", "Sally Brown"],
    ],
    [
      "12pm",
      "4/5",
      false,
      ["James Junaidi", "Omid Mogasemi", "Essam Sleiman", "John Doe"],
      ["Sally Brown"],
    ],
    [
      "1230pm",
      "1/5",
      false,
      ["James Junaidi"],
      ["Omid Mogasemi", "Essam Sleiman", "John Doe", "Sally Brown"],
    ],
  ],
  calendar1_intervals = [
    // NOTE: The 3 different calendar's intervals are identical right now. Haven't had time to randomize them yet
    [
      ["09", false],
      ["09t", false],
      ["10", true],
      ["10t", true],
      ["11", false],
      ["11t", false],
      ["12", false],
      ["12t", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", false],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", true],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", true],
      ["12pm", false],
      ["1230pm", false],
    ],
  ],
  calendar2_intervals = [
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", false],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", true],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", true],
      ["12pm", false],
      ["1230pm", false],
    ],
  ],
  calendar3_intervals = [
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", false],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", true],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", false],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", false],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", false],
      ["12pm", true],
      ["1230pm", false],
    ],
    [
      ["9am", false],
      ["930am", true],
      ["10am", true],
      ["1030am", true],
      ["11am", false],
      ["1130am", true],
      ["12pm", false],
      ["1230pm", false],
    ],
  ];

export default {
  calendar1_intervals,
  calendar2_intervals,
  calendar3_intervals,
};
